import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import LanguageSwitcher from "@/components/ui/LanguageSwitcher";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: LocaleLayoutProps) {
  const { locale } = await params;

  setRequestLocale(locale);

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/emprezel.webp" type="image/svg+xml"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <header>
            <LanguageSwitcher />
          </header>
          {children}

          <Toaster
            className="text-black flex align-center justify-center"
            position="bottom-center"
            toastOptions={{
              style: {
                background: "white",
              },
            }}
          />
          <footer className="footer">
            <p className="paragraph">&copy; {new Date().getFullYear()} All rights reserved.</p>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
